set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
set-option -g renumber-windows on
setw -g pane-base-index 1

set -g mouse on

bind j command-prompt -p "Join current pane with:" "join-pane -s '%%' -h -d"

bind b break-pane

bind x kill-pane

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded."

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",alacritty:RGB,sync"

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection

bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Reduce delay when pressing Escape in Vim
set -sg escape-time 0

# Allow neovim to change window names
set-option -g automatic-rename off
set-option -g status-interval 1
set-option -g automatic-rename-format "#{pane_current_command}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

set -g @plugin 'safanasjev/minimal-tmux-status'

run '~/.config/tmux/plugins/tpm/tpm'
